CREATE TYPE frequency_enum AS ENUM ('daily', 'weekly', 'biweekly', 'monthly', 'bimonthly', 'yearly');

CREATE TABLE public.chore (
    id bigint generated by default as identity not null,
    name text null,
    location_in_house text null,
    frequency frequency_enum null, -- Now using ENUM type
    duration_mins bigint null default '0'::bigint,
    priority integer null,
    due_date date null,
    CONSTRAINT chore_pkey PRIMARY KEY (id),
    CONSTRAINT chore_priority_check CHECK (
        (priority >= 1) AND (priority <= 5)
    )
) TABLESPACE pg_default;

-- Insert pre-populated data into the chore table
INSERT INTO public.chore (name, location_in_house, frequency, duration_mins, priority, due_date)
VALUES 
    ('Mop floors', 'Living Room', 'weekly', 30, 3, '2024-11-01'),
    ('Wash dishes', 'Kitchen', 'daily', 10, 2, '2024-10-28');

create table
  public.roommate (
    id bigint generated by default as identity not null,
    first_name text null,
    last_name text null,
    email text null,
    constraint roommate_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.chore_assignment (
    id bigint generated by default as identity not null,
    chore_id bigint null,
    roommate_id bigint null,
    status text null,
    constraint status_check CHECK (status IN ('pending', 'in_progress', 'completed'))
    constraint chore_assignment_pkey primary key (id),
    constraint chore_assignment_chore_id_fkey foreign key (chore_id) references chore (id),
    constraint chore_assignment_roommate_id_fkey foreign key (roommate_id) references roommate (id),
  ) tablespace pg_default;

create table
  public.bill (
    id bigint generated by default as identity not null,
    cost double precision null,
    due_date timestamp with time zone null default (now() at time zone 'utc'::text),
    bill_type text null,
    message text null,
    constraint bill_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.bill_list (
    id bigint generated by default as identity not null,
    bill_id bigint null,
    roommate_id bigint null,
    status text null,
    constraint bill_list_pkey primary key (id),
    constraint bill_list_bill_id_fkey foreign key (bill_id) references bill (id)
  ) tablespace pg_default;
